### ISSUE TITLE
plugin-enterprise-compatibility@1.2.1 incompatible with probot@9.4.0

### ISSUE THREAD

**Issue by bcoe** [octokit/plugin-enterprise-compatibility.js#25]
If the ` @octokit/plugin-enterprise-compatibility` is installed at `latest`, on an existing probot `9.4.0` application, we begin seeing the following exception:

```bash
TypeError: pluginFunction is not a function
    at /usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/@octokit/rest/lib/constructor.js:26:37
    at Array.forEach (<anonymous>)
    at new Octokit (/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/@octokit/rest/lib/constructor.js:26:11)
    at Object.GitHubAPI (/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/probot/lib/github/index.js:26:19)
    at /usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/build/test/gcf-utils.js:50:38
    at new Promise (<anonymous>)
    at Application.app.auth (/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/build/test/gcf-utils.js:49:34)
    at Application.authenticateEvent (/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/probot/lib/application.js:247:25)
    at Application.<anonymous> (/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/probot/lib/application.js:149:55)
    at step (/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/probot/lib/application.js:43:23)
    at Object.next (/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/probot/lib/application.js:24:53)
    at /usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/probot/lib/application.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/probot/lib/application.js:14:12)
    at EventEmitter.<anonymous> (/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/probot/lib/application.js:140:72)
    at /usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/promise-events/emitter.js:119:65
    at /usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/promise-events/emitter.js:351:67
```

**Comment by gr2m** [comment]
I’m sorry 😐 it’s fixed in the latest probot. I accidentally published a feature version when it should be a breaking one

**Comment by hipstersmoothie** [comment]
Ah ok. I tried updating all my @octokit deps but the build still didn't work.

```ts
packages/core/src/git.ts:69:35 - error TS2345: Argument of type 'typeof enterpriseCompatibility' is not assignable to parameter of type 'Plugin | Plugin[]'.
  Type 'typeof enterpriseCompatibility' is not assignable to type 'Plugin'.
    Types of parameters 'octokit' and 'octokit' are incompatible.
      Type 'Octokit' is missing the following properties from type 'Octokit': graphql, auth

69     const GitHub = Octokit.plugin(enterpriseCompatibility)
```

I'll hold off for a bit

**Comment by hipstersmoothie** [comment]
This is in https://github.com/intuit/auto with the only change is updating this package to latest

**Comment by bcoe** [comment]
@gr2m no worries :smile: I ultimately ended up getting our repo on `9.6.4`, and things seem healthy; just had to address some of the config loading issues I'd brought up previously.

**Comment by gr2m** [comment]
Hey is this still a problem? Or can we close the issue?
